### PR TITLE
Add ability to view and publish In-Page Experiences

### PR DESCRIPTION
**Pull request by Rahmon**
### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

Added In-Page Experiences.

### CODE REVIEW

**Comment by oscarssanchez** [comment]
Hi @Rahmon ,

Can you share more or less the feature scope ?

I see there's new tabs when you are inserting a video and see this message for example: "Please note that you can create new Experiences only from Brightcove.", however I am unsure what are the limits of the feature itself. Is it just fetching the experiences created from Brightcove?

**Comment by Rahmon** [comment]
> Hi @Rahmon ,
> 
> Can you share more or less the feature scope ?
> 
> I see there's new tabs when you are inserting a video and see this message for example: "Please note that you can create new Experiences only from Brightcove.", however I am unsure what are the limits of the feature itself. Is it just fetching the experiences created from Brightcove?

Yes @oscarssanchez . The feature scope is to list the In-Page Experiences and to embed an In-Page Experience to the page.

**Comment by oscarssanchez** [comment]
Hi @Rahmon i'm leaving a comment for each issue that I've found:


### Cannot see details of in page experience videos:

Normally, you would see the details of a video like this:

Screen Shot 2021-11-16 at 19 17 41

However with this feature these are gone:

Screen Shot 2021-11-16 at 19 17 41

Is it intended behavior? Note that both videos are the same.

**Comment by oscarssanchez** [comment]
### Difference between in in page and normal videos

What would be the difference between what is shown in the in page experience tab and normal videos? In the case above, both short and longer videos seem to be showing the same in both tabs. Shouldn't the in page experience be limited to fetch videos that are shorter IIRC? I'm mostly thinking a user could be confused what is the difference between those two tabs

Screen Shot 2021-11-16 at 19 24 52

**Comment by oscarssanchez** [comment]
### Selecting between iframe and JavaScript seems to do nothing:

Selecting JavaScript embed defaults to iframe and toggling between both in the block options seems to do nothing:

Screen Shot 2021-11-16 at 19 48 04

**Comment by Rahmon** [comment]
> ### Selecting between iframe and JavaScript seems to do nothing:
> Selecting JavaScript embed defaults to iframe and toggling between both in the block options seems to do nothing:
> 
> Screen Shot 2021-11-16 at 19 48 04

@oscarssanchez I keep the same behavior (using an iframe) of the videos and playlists. I'd say we can keep this behavior on the editor.

**Review by oscarssanchez — APPROVED** [review]

**Pull request merged**
