### PR TITLE
UX admin enhancements 

### PR DESCRIPTION
**Pull request by ivanlopez**
This pull request accounts for the following enhancements:

- If a large video has been uploaded and appears in the videos list in WordPress while it is still processing then there is a placeholder image shown, but the placeholder doesn’t have any words to indicate the video is processing. 
- There is some max length to the description field, but it is not specified in the plugin. Editing a video simply fails if you send a long description. Likewise the long description has a limit.
- After a successful upload the success message fades away fairly quickly, leaving the only indication that the full progress bar as the only indicator that the upload was successful.
-  The "Start Upload" button should use the same class Publish/Update does on the post editor screen. Start Upload is the next required step after selecting a video, so it should be more noticeable.

### CODE REVIEW

**Comment by JonBellah** [comment]
Code looks good, but we should disable the edit/preview buttons for items that are listed as processing. `display: none;` would be fine.

disable-processing

**Comment by ivanlopez** [comment]
I'll get it updated. I'll also confirm that's not a separate ticket.

**Comment by ivanlopez** [comment]
I need to make a few css tweaks to make sure processing... is always centered vertically.

**Comment by tlovett1** [comment]
+1 to all of this.

**Pull request merged**
