### PR TITLE
Release 2.1.2

### PR DESCRIPTION
**Pull request by oscarssanchez**
### Description of the Change

This PR updates plugin version, README and POT file in order to prepare for 2.1.2 release. 

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by felipeelia — APPROVED** [review]

**Comment by jeffpaul** [comment]
@oscarssanchez does this tentative release also include these [two PRs](https://github.com/10up/brightcove-video-connect/pulls?q=is%3Apr+is%3Aclosed+milestone%3A2.2.0) already merged to `develop` and currently marked for a `2.2.0` release?

**Comment by oscarssanchez** [comment]
Hi @jeffpaul ,

Yes, the release is basically those two bug fixes. Out of the two, one is very important to fix which is why I tagged as a bug fix release. Should tag as 2.2 ? 

Thanks!

**Comment by jeffpaul** [comment]
@oscarssanchez no I think 2.1.2 is fine, I'll just update the milestone reference on those merged PRs so reference info in the repo is accurate.

**Comment by oscarssanchez** [comment]
Thanks @jeffpaul !

**Pull request merged**
