### PR TITLE
Add a target attribute to change shortcode placement

### PR DESCRIPTION
**Pull request by schrapel**
This provides the ability to place a brightcove media button and put the contents of the shortcode into any target value

### CODE REVIEW

**Comment by schrapel** [comment]
@sudar is it possible to get an update on the state of this?

**Comment by sudar** [comment]
@schrapel 

Right now this PR has conflicts.

Please resolve the merge conflicts and I will see if this can be merged as part of next release.

**Comment by schrapel** [comment]
Will do it today!

**Comment by schrapel** [comment]
@sudar I finally had a chance to do this. If you are still unsure about merging this I'd love to demo the feature to you and show how it's possible to embed a video into any custom field you want from this change

**Comment by sudar** [comment]
@schrapel 

Thanks for refreshing this pull request.

> ... put the contents of the shortcode into any target value

By this do you mean into any instance of WordPress post editor?

**Comment by schrapel** [comment]
@sudar Yes, if you choose the target on the button that opens the Brightcove model you can put it into any instance. This allows us to use advanced custom fields to store a Brightcove video.

**Comment by sudar** [comment]
@schrapel 

Thanks for the explanation and the PR. I have merged the code.

It will be released as part of next release.

**Pull request merged**
