### PR TITLE
Make sure that history hasn't started before starting.

### PR DESCRIPTION
**Pull request by ninnypants**
If other plugins have already run `Backbone.history.start()` then calling `Backbone.history.start()` will throw an error causing issues with other plugins that try to use the media modal.

### CODE REVIEW

**Comment by sudar** [comment]
@ninnypants 

Which plugin was causing this issue?

I am trying to replicate the issue so that I can test it

**Comment by ninnypants** [comment]
@sudar It was TL's https://wordpress.org/plugins/custom-contact-forms/ that was starting history before brightcove for us.

**Comment by sudar** [comment]
@ninnypants 

Thanks for sending the link.

Right now the PR has a merge conflict. Once it is resolved I can merge it.

**Comment by ninnypants** [comment]
@sudar It was TL's https://wordpress.org/plugins/custom-contact-forms/ that was starting history before brightcove for us.

**Comment by ninnypants** [comment]
@sudar hey just ran into this on a project again, so I updated this branch with the latest master. Have you had a chance to test so that we can get this merged?

**Comment by sudar** [comment]
@ninnypants Thanks.

**Pull request merged**
